backend:
  name: github
  repo: PavloYarmolyk/PavloArtworks
  branch: main

media_folder: src/images
public_folder: ../images

collections:
  - name: Bio
    label: Bio
    folder: src/bio
    create: false
    slug: '{{year}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'bio' }
      - { label: 'Slug', name: 'BioSlug', widget: 'string' }
      - { label: 'BioTitle', name: 'BioTitle', widget: 'string' }
      - {
          label: 'Bio Image',
          name: 'bioImage',
          widget: 'image',
          hint: 'Only files *.WEBP , to convert your image go to the : https://squoosh.app/ ',
        }
      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main Bio info goes here.' }
  - name: specialArt
    label: Special Art
    folder: src/Artwork_specialArt
    create: true
    slug: '{{year}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'artwork' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Featured-Image',
          name: 'featured',
          widget: 'image',
          hint: 'Only files *.WEBP , to convert your image go to the : https://squoosh.app/ ',
        }
      - { label: 'Made of and Where', name: 'made_of_and_where' }
      - { label: 'Tags', name: 'tags', widget: 'list', hint: 'Separate by comma' }
      - label: 'Slider'
        name: 'sliderImage'
        widget: list
        fields:
          - { label: Image, name: image, widget: image }
      - { label: 'Description', name: 'body', widget: 'markdown', required: false }
      - { label: 'Additional Description', name: 'AdditionalDescription', required: false }
  - name: painting
    label: Painting
    folder: src/Artwork_paintings
    create: true
    slug: '{{year}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'artwork' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Featured-Image',
          name: 'featured',
          widget: 'image',
          hint: 'Only files *.WEBP , to convert your image go to the : https://squoosh.app/ ',
        }
      - { label: 'Made of and Where', name: 'made_of_and_where' }
      - { label: 'Tags', name: 'tags', widget: 'list', hint: 'Separate by comma' }
      - label: 'Slider'
        name: 'sliderImage'
        widget: list
        fields:
          - { label: Image, name: image, widget: image }
      - { label: 'Description', name: 'body', widget: 'markdown', required: false }
      - { label: 'Additional Description', name: 'AdditionalDescription', required: false }
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Hero Section'
        name: 'hero'
        file: 'src/mock/hero.json'
        fields:
          - { label: OverTitle, name: overTitle, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: AfterTitle, name: afterTitle, widget: string }
          - { label: ButtonOne, name: buttonOne, widget: string }
          - { label: Link_to_ButtonOne, name: link_to_ButtonOne, widget: string }
          - { label: ButtonTwo, name: buttonTwo, widget: string }
          - { label: Link_to_ButtonTwo, name: link_to_ButtonTwo, widget: string }
      - label: 'Footer Info'
        name: 'footer'
        file: 'src/mock/footer.json'
        fields:
          - { label: email, name: email, widget: string }
          - { label: 'phone_Number', name: 'phone_Number', widget: 'text' }
          - { label: Facebook Page, name: fbLink, widget: string }
          - { label: 'Instagram Page', name: 'instaLink', widget: 'text' }
      - label: 'Header Info'
        name: 'header'
        file: 'src/mock/header.json'
        fields:
          - { label: Logo, name: logo, widget: image }
          - { label: Logo_Description, name: alt, widget: string }
          - { label: Logo_Link_to, name: logo_link_to, widget: string }
          - label: Menu Tab
            name: menu_tab
            widget: list
            fields:
              - { label: Nav_Title, name: nav_title, widget: string }
              - { label: Nav_Link, name: nav_link, widget: string }
